import "./globals.css";
import type { Metadata } from "next";
import HeroUIWrapper from "@/providers/HeroUIWrapper";
import ManropeFont from "@/providers/ManropeFont";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader easing="ease" showSpinner={false} />
        <ManropeFont>
          <HeroUIWrapper>{children}</HeroUIWrapper>
        </ManropeFont>
      </body>
    </html>
  );
}
